import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#0C0C0C',
  '--slot4-page-text': '#FAF4EF',
  '--slot4-panel-bg': '#1A0E08',
  '--slot4-surface-bg': '#221408',
  '--slot4-muted-text': '#B89070',
  '--slot4-soft-muted-text': '#7A5840',
  '--slot4-accent': '#F2613F',
  '--slot4-accent-fill': '#F2613F',
  '--slot4-accent-soft': 'rgba(242,97,63,0.12)',
  '--slot4-on-accent': '#FAF4EF',
  '--slot4-dark-bg': '#0C0C0C',
  '--slot4-dark-text': '#FAF4EF',
  '--slot4-media-bg': '#2A1810',
  '--slot4-cream': '#1A0E08',
  '--slot4-warm': '#170D06',
  '--slot4-lavender': '#1A0E08',
  '--slot4-gray': '#170D06',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#0C0C0C',
  '--editable-page-text': '#FAF4EF',
  '--editable-container': '1400px',
  '--editable-border': 'rgba(242,97,63,0.18)',
  '--editable-nav-bg': '#0C0C0C',
  '--editable-nav-text': '#FAF4EF',
  '--editable-nav-active': '#F2613F',
  '--editable-nav-active-text': '#FAF4EF',
  '--editable-cta-bg': '#F2613F',
  '--editable-cta-text': '#FAF4EF',
  '--editable-search-bg': '#221408',
  '--editable-footer-bg': '#0A0906',
  '--editable-footer-text': '#FAF4EF',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-on-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/8',
  shadow: 'shadow-[0_1px_3px_rgba(0,0,0,0.5)]',
  shadowStrong: 'shadow-[0_4px_18px_rgba(0,0,0,0.7)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.82))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen bg-[var(--slot4-page-bg)] text-[var(--slot4-page-text)]`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-4 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[160px] shrink-0 snap-start sm:w-[180px]',
  },
  type: {
    eyebrow: 'text-[11px] font-bold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-black leading-[1.04] tracking-[-0.03em] sm:text-5xl lg:text-[3.5rem]',
    sectionTitle: 'text-2xl font-extrabold tracking-[-0.02em] sm:text-3xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-xl border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] shadow-[0_2px_8px_rgba(0,0,0,0.5)]`,
    soft: `rounded-xl border border-[var(--editable-border)] bg-[var(--slot4-panel-bg)]`,
    dark: `rounded-xl bg-[var(--slot4-dark-bg)] shadow-[0_4px_24px_rgba(0,0,0,0.7)]`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-110 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-110 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-xl bg-[var(--slot4-media-bg)]`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_12px_32px_rgba(0,0,0,0.6)]',
    fade: 'transition duration-200 hover:opacity-90',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the Shutterfly reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
